version: "3.8"

services:
  app:
    build: .
    container_name: habittracker
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=habittracker_db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    container_name: habittracker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: habittracker_db
    ports:
      - "3306:3306"
